name: Create git tag, run scans and tests on Go repos

on:
  push:
    branches:
      - master
      
jobs:
  set_stage:
    name: Determine Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set semantic_version
        id: branch_check
        run: |
          semantic_version=$(cat version)
          echo "semantic_version=$semantic_version" >> $GITHUB_OUTPUT
      - name: Print Semantic version
        run: echo "semantic_version for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.semantic_version }}'"
    outputs:
      semantic_version: ${{ steps.branch_check.outputs.semantic_version }}
      
  # Test, scan, build and push Go related repos or compiled binaries
  ci-ct-job-for-go-repos:
    runs-on: ubuntu-latest
    needs: [set_stage]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install az
        run: |
          sudo apt-get install -y curl jq
          sudo curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Login as service principal
        run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Retrieve and output acccess token
        id: retrieve_access_token
        run: echo "access_token=$(az account get-access-token | jq -r '.accessToken')" >> $GITHUB_OUTPUT
      - name: Test Go repository
        uses: MGTheTrain/public-github-actions/.github/actions/test-go-repository@main
        with:
          TEST_WORKING_DIRECTORY: ./mgtt/test
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          AZURE_ACCESS_TOKEN: ${{ steps.retrieve_access_token.outputs.access_token }}
  create-git-tags-from-version-file-job:
    runs-on: ubuntu-latest
    needs: [set_stage]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create git tag from version file
        uses: MGTheTrain/public-github-actions/.github/actions/create-git-tag-from-version-file@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}